"""Emit a minimal scenerio.gcx for a custom stage.

We hand-craft a tiny .gcl text and run the existing
port/gcl_tools/gcl_compile.py over it (no point reinventing the
bytecode emitter — it's tested against the disc binaries).

The generated scenerio.gcl boots a stage that just sits idle so the
editor can load it; no characters, no triggers, no demo logic. The
KMD that this stage maps to is identified by `kmd_hash` (16-bit GV
StrCode of the KMD's DAR id name).
"""

import sys
from pathlib import Path


def write_gcx(stage_name: str, kmd_hash: int,
              source_path: Path | None = None) -> bytes:
    """Compile scenerio.gcl bytes.

    If `source_path` points at an existing .gcl file, compile it as-is.
    Otherwise emit a minimal stub that boots a stage that just sits idle
    so the editor can load it; no characters, no triggers, no demo
    logic. The stage's KMD is identified by `kmd_hash` (16-bit GV
    StrCode of the KMD's DAR id name)."""
    # Make sure port/gcl_tools is on sys.path before importing.
    repo = Path(__file__).resolve().parent.parent.parent
    gcl_tools = repo / "port" / "gcl_tools"
    if str(gcl_tools) not in sys.path:
        sys.path.insert(0, str(gcl_tools))

    from gcl_parser import parse                  # noqa: E402
    from gcl_compile import GclComp               # noqa: E402

    if source_path is not None and Path(source_path).is_file():
        src = Path(source_path).read_text()
    else:
        # The GCL parser requires proc names of the form `sub_XXXX` (hash).
        # init_ve/scenerio.gcl is the minimal real example — one proc + one
        # script block. We mirror that shape and tag it with a stable hash
        # derived from the stage name.
        init_proc_id = (kmd_hash ^ 0x8CD4) & 0xFFFF
        src = (
            "# auto-generated by tools/import_stage.py — do not edit by hand\n"
            f"proc sub_{init_proc_id:04X} {{\n"
            "    eval($f:000001 = b:0)\n"
            "}\n"
            "\n"
            "script {\n"
            f"    map -d $s:{kmd_hash:04X}\n"
            "}\n"
        )

    tree = parse(src)
    comp = GclComp(align4=True)
    return bytes(comp.compile_file(tree))
