"""Mapping between MGS 2-byte character codes and Unicode glyphs.

MGS text is **not** Shift-JIS or EUC-JP — it's a custom encoding where each
2-byte big-endian code (high byte >= 0x80) is a glyph index into a stage-
specific font bitmap. ASCII bytes (< 0x80) encode themselves.

This table is seeded from the explicit comments in
[source/font/font.c](../../source/font/font.c), primarily
`get_rubi_char_index_800457B4` which documents:

    0x8201 .. 0x824D  'ァ' .. 'ロ'   (Katakana, sequential)
    0x824F            'ヲ'
    0x8253            'ン'
    0x9001            '　'           (fullwidth space)

Codes not in the table round-trip through the `{XXXX}` literal syntax, so
the decoder is always lossless even when we don't know a glyph's meaning.
Extend the table below when you learn new mappings.
"""

CODE_TO_CHAR: dict[int, str] = {}
CHAR_TO_CODE: dict[str, int] = {}


def _add(code: int, ch: str) -> None:
    # Each char must round-trip 1:1; collisions would break the encoder.
    if code in CODE_TO_CHAR:
        raise ValueError(f"duplicate code 0x{code:04X}")
    if ch in CHAR_TO_CODE:
        raise ValueError(f"duplicate char {ch!r} (0x{ord(ch):04X})")
    CODE_TO_CHAR[code] = ch
    CHAR_TO_CODE[ch] = code


# Katakana ァ..ロ — sequential. font.c comment documents the endpoints and
# the MGS range 0x8201..0x824D is exactly 0x4D chars wide, matching the
# Unicode block U+30A1..U+30ED.
for _i in range(0x4D):
    _add(0x8201 + _i, chr(0x30A1 + _i))

# Explicit singletons (comments in get_rubi_char_index_800457B4).
_add(0x824F, "ヲ")
_add(0x8253, "ン")

# Fullwidth space (comment says 0x9001 = '　').
_add(0x9001, "\u3000")

# Optionally merge in mappings derived from aligning our output against
# WantedThing's decompiled .gcl corpus (generated by derive_table.py).
# The file is allowed to be absent.
def _to_fullwidth(ch: str) -> str:
    """WantedThing sometimes emitted ASCII where the game renders a
    fullwidth glyph (e.g. `7` instead of `７`). Normalise so the char
    doesn't collide with single-byte ASCII encoding during round-trip.
    """
    cp = ord(ch)
    if 0x21 <= cp <= 0x7E:              # printable ASCII → fullwidth
        return chr(cp - 0x21 + 0xFF01)
    return ch


try:
    from .chars_derived import DERIVED_CODE_TO_CHAR as _DERIVED
    for _code, _raw in _DERIVED.items():
        _ch = _to_fullwidth(_raw) if len(_raw) == 1 else _raw
        if ord(_ch) < 0x80:
            continue                    # still ASCII (e.g. space) — skip
        if _code in CODE_TO_CHAR or _ch in CHAR_TO_CODE:
            continue                    # seed wins over derived on conflict
        _add(_code, _ch)
except ImportError:
    pass
